### ISSUE TITLE
Please add a portable .zip version 

### ISSUE THREAD

**Issue by Paradoxum** [R2NorthstarTools/FlightCore#461]
![image](https://github.com/R2NorthstarTools/FlightCore/assets/6451395/05ef3994-ae0c-4983-b194-fa6e914e3539)

I'm unable to solve this error no matter what I do I've gone through 10 google pages of the issue. Please just add a zip file with the contents.

**Comment by GeckoEidechse** [comment]
IIRC the error message you are seeing is due to installation from MSI packages being blocked on your Windows install due to some group policy. I think someone else had this issue before. Not sure what they did to solve this. If we figure out a solution, we should add it to the docs ^^

Either way I'm not planning to offer a portable install as it's just too much additional overhead for me to maintain. If someone else is willing to pick up that maintenance burden, I'm happy to assist.

Otherwise I recommend just using another mod-manager listed on [northstar.tf](https://northstar.tf/).

**Comment by GeckoEidechse** [comment]
Tracking documenting a solution for that error message here: #462 

As for offering a portable version, as I said, someone else is free to pick that up but I personally don't have the time to maintain it.

**Comment by Paradoxum** [comment]
I'm ignorant to how it is installed, but isn't it as simple as just taking the extracted files from the .msi and zipping them up? 
I think it is a group policy setting, I changed something which made my account an always elevated admin account (Win 11), sort of like 'god mode', I don't know why it affects this though. I also can't find the damn policy to change it back and my chrome history got cleared. If anyone knows how the other guy fixed it chime in please.

Also, I don't use any mods personally, I just wanna login and play on the northstar servers now and again, do I even need flightcore or something else can't I just install northstar on its own? I'm also kind of ignorant about northstar and everything I only just reinstalled the game after years.

Thanks for your work.

**Comment by GeckoEidechse** [comment]
> I'm ignorant to how it is installed, but isn't it as simple as just taking the extracted files from the .msi and zipping them up?

Unfortunately no. While I think there's ways for extracting the files inside the MSI and Tauri might also offer an exe artifact, there's still the fac that for FlightCore to run, WebView2 must be installed. The `.msi` installer takes care of that including installing the WebView2 dependency. A lone exe would require WebView2 to be already installed which is rarely the case.

Knowing endusers if I offer an `.exe` as a download options there will be some picking that over the `.msi` as they are more familiar with the format, and then upon installation they will be confused why FlightCore won't launch (due to missing WebView2). Also I have a whole GitHub Action set up for automating making releases and that would also have to be adjusted to build and upload additional artifacts.

Sidenote, you really wanna look into reverting the change regarding your Windows account. Running everything as admin sounds like a huge security risk.

> Also, I don't use any mods personally, I just wanna login and play on the northstar servers now and again, do I even need flightcore or something else can't I just install northstar on its own?

You can just install Northstar manually following the [instructions on the wiki](https://r2northstar.gitbook.io/r2northstar-wiki/installing-northstar/manual-installation).
